export const PotenciaMap = {
    'Air fryer': 1400,
    'Ar-condicionado': 2000,
    'Chapa': 1500,
    'Chuveiro elétrico': 5500,
    'Computador': 400,
    'Consoles de videogame': 150,
    'Forno elétrico': 1800,
    'Freezer': 300,
    'Geladeira de 1 porta': 120,
    'Geladeira de duas portas': 200,
    'Grelha elétrica': 1400,
    'Lâmpada fluorescente': 20,
    'Lâmpada incandescente': 60,
    'Lâmpada LED': 1,
    'Liquidificador': 500,
    'Modem de Wi-Fi': 15,
    'Televisão': 100,
    'Ventilador': 50,
    'Ventilador de teto': 75,
    'Carregador de celular': 5,
    'Carregador de notebook': 65,
    'Impressora': 80,
    'Modelador de cabelo': 120,
    'Secador de cabelo': 1800
};